environment: development

apphost: k8s

products:
  label:
    name: aspnet3core

  container:
    name: aspnet3
    pullPolicy: IfNotPresent
    image: deathstroke45/petshopproducts
    tag: latest
    port: 80
  replicas: 1

  service:
    port: 8888
    type: NodePort

orders:
  label:
    name: aspnet3core

  container:
    name: aspnet3-orders
    pullPolicy: IfNotPresent
    image: deathstroke45/petshoporders
    tag: latest
    port: 80
  replicas: 1

  service:
    port: 8889
    type: NodePort
