apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: petshop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - ssltest.theproindia.com
      secretName: shop-certs
  rules:
   - host: ssltest.theproindia.com
     http:
      paths: 
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-products-service
          servicePort: {{ .Values.products.service.port }}
      - path: /orders
        backend:
          serviceName: {{ .Release.Name }}-orders-service
          servicePort: {{ .Values.orders.service.port }}